#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Jun 22 12:39:54 PKT 2026
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim top_module_tb_behav -key {Behavioral:sim_1:Functional:top_module_tb} -tclbatch top_module_tb.tcl -view /home/pc-11/Desktop/Computer Architecture/Multicycle_processor_Final/Multicycle_processor2/top_module_tb_behav.wcfg -log simulate.log"
xsim top_module_tb_behav -key {Behavioral:sim_1:Functional:top_module_tb} -tclbatch top_module_tb.tcl -view /home/pc-11/Desktop/Computer Architecture/Multicycle_processor_Final/Multicycle_processor2/top_module_tb_behav.wcfg -log simulate.log

